// snapshot.js — the shareable Capacity Snapshot (the "credential" artifact).
//
// Forma's B2B thesis is a capacity credential a person could show an employer.
// This assembles the individual's own formation profile into one consolidated,
// honest summary they can print, save as PDF, or copy as text. It is generated
// BY the person, FROM their own local data — Forma never holds or transmits it.
//
// Privacy guardrail: the optional Interior Life track is ALWAYS excluded here —
// a shareable/employer-facing credential must never expose someone's spiritual
// data, regardless of whether they enabled that track for their own use.
//
// Pure functions, no DOM — fully testable.

import { activeDomainIds, getDomain, bandFor } from './domains.js';
import { formationIndex } from './scoring.js';
import { aiReadinessOf } from './team.js';
import { confidence } from './reliability.js';
import { domainTrend, daysBetween, todayStr } from './progress.js';

export function buildSnapshot(profile, today = todayStr()) {
  const scores = profile.domainScores || {};
  const faith = !!(profile.settings && profile.settings.faithTrack);
  // Active domains EXCEPT interior (never shareable), with a real score.
  const ids = activeDomainIds(faith).filter((id) => id !== 'interior' && scores[id] != null);
  const baseScores = (profile.baseline && profile.baseline.domainScores) || {};
  const domains = ids.map((id) => {
    const t = domainTrend(profile.history || [], id);
    // Anchor "since start" on the BASELINE score, not the first daily session —
    // history doesn't include the baseline point (applyBaseline seeds only
    // indexHistory), so domainTrend.delta would silently drop the baseline→
    // session-1 movement and show "±0 since start" on an improved score. Mirrors
    // proof.js's baseline anchor.
    const base = baseScores[id] != null ? baseScores[id] : (t.first != null ? t.first : null);
    return {
      id,
      name: getDomain(id).name,
      score: scores[id],
      band: bandFor(scores[id]).label,
      confidence: confidence(profile, id).label,
      delta: base != null ? scores[id] - base : 0,
    };
  }).sort((a, b) => b.score - a.score);

  const since = profile.baseline ? profile.baseline.date : null;
  // AI-Readiness / Formation Index over the shareable (non-interior) scores only.
  const shareScores = {};
  ids.forEach((id) => { shareScores[id] = scores[id]; });

  return {
    name: (profile.settings && profile.settings.name) || null,
    since,
    days: since ? daysBetween(since, today) : 0,
    sessionCount: (profile.sessions || []).length,
    formationIndex: formationIndex(shareScores),
    aiReadiness: aiReadinessOf(shareScores),
    domains,
    strengths: domains.slice(0, 2).map((d) => d.name),
    growthEdges: domains.slice().reverse().slice(0, 2).map((d) => d.name),
  };
}

// A plain-text rendering of the snapshot — for the "copy" affordance, so it can
// be pasted into an email or application. Honest, compact, self-generated.
export function snapshotText(snap) {
  const lines = [];
  lines.push(`FORMA — Capacity Snapshot${snap.name ? ' · ' + snap.name : ''}`);
  if (snap.since) lines.push(`${snap.sessionCount} session${snap.sessionCount === 1 ? '' : 's'} over ${snap.days} day${snap.days === 1 ? '' : 's'}`);
  lines.push('');
  lines.push(`Formation Index: ${snap.formationIndex}`);
  if (snap.aiReadiness != null) lines.push(`AI-Readiness: ${snap.aiReadiness}`);
  lines.push('');
  lines.push('Capacities:');
  snap.domains.forEach((d) => {
    const dl = d.delta > 0 ? ` (+${d.delta} since start)` : d.delta < 0 ? ` (${d.delta} since start)` : '';
    lines.push(`  - ${d.name}: ${d.score} (${d.band})${dl}`);
  });
  lines.push('');
  lines.push('Measurement for formation, not diagnosis. Generated by the individual from their own data.');
  return lines.join('\n');
}
