// demo.js — a deterministic SAMPLE profile for previewing the populated app.
//
// WHY: an investor or prospective user should see the whole of Forma — radar,
// trends, coach, Progress — without first doing the baseline and weeks of
// practice. Demo Mode (app.js) swaps this sample into memory.
//
// NON-DESTRUCTIVE: Demo Mode never writes to disk. app.js's save() is a no-op
// while demo is on, so the real profile in localStorage is never touched; the
// sample lives only in memory and vanishes on reload or exit.
//
// HONEST: every number here is ILLUSTRATIVE — generated to show the interface,
// not a measurement of any real person. The app shows a persistent "sample data"
// banner the whole time, so it can't be mistaken for a real profile.
//
// GUARDRAIL: the optional Spiritual Life / interior track is OFF here, and no
// interior/faith content appears anywhere — the same wall the real app enforces.
//
// Deterministic: no RNG (seeded by index, like team.js's sampleCohort), so the
// sample is identical every time and stable to test.

import { DOMAINS } from './domains.js';
import { formationIndex } from './scoring.js';
import { todayStr } from './progress.js';
import { bandIndex } from './milestones.js';

const DAY_MS = 86400000;

// ---- THE SAMPLE SPEC ---------------------------------------------------------
// One auditable object holds all of the sample's numbers and copy, so the whole
// fiction is easy to read, tune, and verify against the brand. Generated by the
// validity / coach-voice / design review (workflow forma-demo-spec).
export const SPEC = {
  persona: {
    name: 'Daniel R.',
    role: 'Senior product manager',
    oneLine: 'A mid-career PM who came to Forma after noticing his focus had gone shallow and his patience short, wanting to track whether deliberate practice actually moves the needle.',
  },
  // Current 0-100 per capacity — a lumpy, believable radar. Strengths: Values 74,
  // Reading 71, Judgment 66, Presence 63. Genuine growth areas (the lows that
  // brought him in): Emotional Regulation 41, Frustration Tolerance 44, Attention 48.
  current: {
    attention: 48, memory: 57, reading: 71, persistence: 44, judgment: 66,
    ai_autonomy: 52, presence: 63, communication: 58, emotion_regulation: 41, values: 74,
  },
  // ~90 days ago. Mostly lower (real, modest growth), but HONEST and non-monotonic:
  // Presence is essentially flat (62->63), Emotional Regulation is actually DOWN
  // (45->41) — a hard season the instrument surfaces rather than smooths over.
  baseline: {
    attention: 41, memory: 49, reading: 65, persistence: 38, judgment: 61,
    ai_autonomy: 47, presence: 62, communication: 51, emotion_regulation: 45, values: 68,
  },
  // Formation Index per week, oldest first, ~90 days. Rises 51->57 but bumpy: an
  // early dip (wk3), a mid-run plateau (wks7-9), a small pullback (wk10). Not a line.
  weeklyIndex: [51, 52, 50, 53, 54, 53, 54, 55, 55, 54, 56, 57, 57],
  // Target streak — actually COMPUTED from the 90-day practice pattern in buildPractice
  // (so the displayed streak can never contradict the session dates); a test asserts they match.
  streak: { current: 6, longest: 17 },
  focusCheck: { count: 12, medianMsLow: 372, medianMsHigh: 521, scoreLow: 49, scoreHigh: 72 },
  // The general "Today" coach thread — solution-focused, warm, specific. Anchors on
  // his STEADIEST capacity (Relational Presence), without overclaiming it as #1. No interior.
  coachGeneral: [
    { role: 'coach', content: 'You stayed with people better than almost anything you did this stretch — Relational Presence is your steadiest capacity, and it held even on your busiest weeks. That kind of staying-power with someone is rare. When did being with a person, without trying to fix it, go best for you lately?' },
    { role: 'user', content: 'Probably my one-on-one with Priya on Tuesday. I just listened instead of jumping to solutions for once.' },
    { role: 'coach', content: 'That’s worth noticing — you didn’t reach for the fix, and the conversation was better for it. What was different about Tuesday that let you do that? If you can name the one thing, you can set it up again on purpose.' },
    { role: 'user', content: 'Honestly I think I just hadn’t checked my phone right before. I went in with a clear head.' },
    { role: 'coach', content: 'Then you already found the lever — a clear head going in, not a longer to-do list. What would it cost you to leave the phone at your desk before your next one-on-one and see if it holds?' },
  ],
  // Reading is a STRENGTH (71). The coaching is about an eroded reading HABIT
  // (skimming, AI summaries), NOT a weak score — consistent with the number.
  coachDomainId: 'reading',
  coachDomain: [
    { role: 'coach', content: 'You just finished the deep-reading passage, and your comprehension is genuinely strong — Deep Reading is one of your higher capacities. But the same pattern showed up that’s been there for weeks: you read the opening closely, then your speed climbs toward the end and the detail questions slip. The skill is there. What I’m curious about is the habit — when in your real week do you actually read something slowly, all the way through?' },
    { role: 'user', content: 'Almost never anymore. I skim everything. I’ll read the summary an AI gives me and tell myself I’ll read the real thing later. I never do.' },
    { role: 'coach', content: 'That’s honest, and it’s most of the work — you can see the trade you’re making. Skimming isn’t the enemy; living only in summaries is, because the thinking happens inside the long argument, not the recap. Here’s one small thing: pick one article this week that actually matters to you, and read just the first three pages on paper or full-screen, phone in another room. Not the whole thing — just far enough to feel what reading at depth is like again. Would you try that with something you’d genuinely want to have read?' },
  ],
  goals: [
    { domain: 'reading', text: 'Read one real article a week to the end on full screen, phone in another room — no summary first.' },
    { domain: 'emotion_regulation', text: 'When a deadline spikes my stress, take three slow breaths and name the feeling before I reply to the thread.' },
    { domain: 'ai_autonomy', text: 'On one task a day, draft my own first version before I open an AI tool, so the thinking starts as mine.' },
  ],
  noticing: 'Your Relational Presence and Judgment have held steady through the run — both still Strong — while the most room to grow right now is in Emotional Regulation and Frustration Tolerance. Your reading comprehension is strong; the practice of reading deeply is the habit worth rebuilding.',
  // Design / chrome copy. The word "Sample" and the fictional name are literally present — honesty over subtlety.
  bannerText: 'Sample profile — “Daniel R.” is fictional. These numbers are illustrative, not a real measurement.',
  exitCta: 'Exit sample',
  exitToast: 'Back to your own Forma.',
  welcomeButton: 'See a sample profile',
  welcomeButtonSub: 'Explore the whole app, already populated — a fictional example, no baseline required.',
  settingsLabel: 'Open sample profile',
  settingsHelp: 'Loads a fictional example so you can show Forma fully populated. Your own data is untouched — exit anytime to return to it.',
  honestyNote: 'Every score, trend, and coach line here is generated to demonstrate the interface — it isn’t a measurement of anyone, and “Daniel R.” is not a real person.',
};

function dayStr(today, daysAgo) {
  return todayStr(new Date(today.getTime() - daysAgo * DAY_MS));
}
function isoAt(today, daysAgo, hour) {
  const d = new Date(today.getTime() - daysAgo * DAY_MS);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

// A representative exercise type per capacity (all real types), so Recent
// sessions and per-capacity threads read naturally.
const TYPE_FOR = {
  attention: 'attend', memory: 'span', reading: 'reading', persistence: 'series',
  judgment: 'crt', ai_autonomy: 'reliance', presence: 'contemplation',
  communication: 'comm', emotion_regulation: 'steu', values: 'reflection',
};

// A believable 90-day adherence pattern (deterministic, no RNG): a strong early
// 17-day run (the longest streak), a realistic ~5-of-7 cadence through the middle,
// one lapse week (life happened), and a solid recent 6-day run (the current streak).
// Yields ~55 sessions across the full 90 days — a seasoned user, not a 9-session one.
function practiced(daysAgo) {
  if (daysAgo >= 73) return true;                    // days 89..73: the 17-day early run
  if (daysAgo >= 50 && daysAgo <= 56) return false;  // a lapse week — honest, not a perfect record
  if (daysAgo <= 5) return true;                     // the recent 6-day run
  if (daysAgo === 6) return false;                   // a rest day, so the current streak is exactly 6
  const m = daysAgo % 7;
  return !(m === 2 || m === 5);                      // otherwise ~5 of every 7 days
}

// Build the full 90-day practice record: the scored sessions AND the per-capacity
// longitudinal log derived from them (one history row per scored session — exactly how
// the real app records history via applySession, so the sparklines show the genuine
// baseline->current climb across the whole window, not just the last few days). Streak is
// COMPUTED from the practice days, so the displayed streak can't contradict the dates.
function buildPractice(today) {
  const ids = DOMAINS.map((d) => d.id).filter((id) => SPEC.current[id] != null);
  const days = [];
  for (let d = 89; d >= 0; d--) if (practiced(d)) days.push(d); // oldest -> newest
  const W = SPEC.weeklyIndex;
  const sessions = [];
  const history = [];
  days.forEach((daysAgo, i) => {
    const id = ids[i % ids.length]; // even rotation across the ten capacities
    const from = SPEC.baseline[id] != null ? SPEC.baseline[id] : SPEC.current[id];
    const to = SPEC.current[id];
    const t = (90 - daysAgo) / 90; // 0 at the baseline -> ~1 today
    const wob = ((id.length * 7 + daysAgo * 13) % 7) - 3; // -3..3, deterministic
    const nd = Math.max(0, Math.min(100, Math.round(from + (to - from) * t + wob)));
    const raw = Math.max(0, Math.min(100, nd + (((i * 11 + id.length * 5) % 11) - 5)));
    const fi = W[Math.min(W.length - 1, Math.round(t * (W.length - 1)))];
    const type = TYPE_FOR[id] || 'reflection';
    sessions.push({
      date: dayStr(today, daysAgo), hour: 8 + (i % 6), ts: isoAt(today, daysAgo, 8 + (i % 6)),
      exerciseId: 'demo-' + id + '-' + daysAgo, type, domain: id,
      rawScore: raw, prevDomainScore: nd, newDomainScore: nd, priorBandPeak: bandIndex(nd),
      unscored: false, response: {},
    });
    history.push({ date: dayStr(today, daysAgo), domain: id, exerciseType: type, rawScore: raw, newDomainScore: nd, formationIndex: fi });
  });
  // Pin each capacity's EARLIEST point to its baseline and its LATEST to its current
  // score, so the sparkline runs from where it started to where the scale now sits and
  // the per-capacity delta equals the true baseline->current change the SPEC intends
  // (presence +1 = flat, emotion_regulation -4 = down) — the wobble shouldn't distort the
  // honest endpoints.
  ids.forEach((id) => {
    const from = SPEC.baseline[id] != null ? SPEC.baseline[id] : SPEC.current[id];
    for (let i = 0; i < sessions.length; i++) { if (sessions[i].domain === id) { sessions[i].newDomainScore = from; break; } }
    for (let i = 0; i < history.length; i++) { if (history[i].domain === id) { history[i].newDomainScore = from; break; } }
    for (let i = sessions.length - 1; i >= 0; i--) { if (sessions[i].domain === id) { sessions[i].newDomainScore = SPEC.current[id]; break; } }
    for (let i = history.length - 1; i >= 0; i--) { if (history[i].domain === id) { history[i].newDomainScore = SPEC.current[id]; break; } }
  });
  // Streak computed FROM the practice days: current = consecutive days ending today;
  // longest = the longest consecutive run anywhere in the window.
  const set = new Set(days);
  let current = 0; while (set.has(current)) current++;
  let longest = 0, run = 0;
  for (let d = 0; d <= 89; d++) { if (set.has(d)) { run++; if (run > longest) longest = run; } else run = 0; }
  return { sessions, history, streak: { current, longest, lastDate: dayStr(today, 0) } };
}

// Construct the full sample profile. `today` is injectable for stable tests.
export function buildDemoProfile(today = new Date()) {
  const practice = buildPractice(today); // ~55 scored sessions + derived history across 90 days
  const p = {
    version: 1,
    createdAt: isoAt(today, 92, 9),
    demo: true, // an in-memory marker; the real profile never carries this
    settings: { provider: 'anthropic', apiKey: '', model: 'claude-opus-4-8', name: SPEC.persona.name, faithTrack: false, researchEndpoint: '' },
    baseline: { date: dayStr(today, 90), domainScores: { ...SPEC.baseline }, responses: {}, method: 'quick' },
    domainScores: { ...SPEC.current },
    sessions: practice.sessions,
    history: practice.history,
    indexHistory: [],
    focusChecks: [],
    plan: null,
    goals: SPEC.goals.map((g, i) => ({ id: 'demo-goal-' + i, domain: g.domain, text: g.text, createdAt: isoAt(today, 30 - i * 6, 9), done: false })),
    streak: practice.streak,
    coachLog: SPEC.coachGeneral.map((m, i) => ({ role: m.role, content: m.content, ts: isoAt(today, 0, 8 + i) })),
    coachThreads: { [SPEC.coachDomainId]: SPEC.coachDomain.map((m, i) => ({ role: m.role, content: m.content, ts: isoAt(today, 1, 17 + i) })) },
    coachHistory: {},
    coachDay: dayStr(today, 0),
    research: { consent: false, consentedAt: null, demographics: {}, queue: [], installId: '', nextSeq: 0 },
    contact: { consent: false, email: '', consentedAt: null },
    release: { consent: false, recipient: '', scope: 'snapshot', snapshot: null, consentedAt: null },
    bandPeak: {},
  };

  // High-water band latch per capacity, so milestone checks don't misfire.
  DOMAINS.forEach((d) => { if (p.domainScores[d.id] != null) p.bandPeak[d.id] = bandIndex(p.domainScores[d.id]); });

  // Index trend across ~90 days, oldest first. The final point is reconciled to
  // the true mean of the current scores, so the headline number is honest.
  const W = SPEC.weeklyIndex;
  W.forEach((fi, i) => {
    const daysAgo = Math.round(90 - (i * 90) / (W.length - 1));
    p.indexHistory.push({ date: dayStr(today, daysAgo), formationIndex: fi });
  });
  p.indexHistory[p.indexHistory.length - 1].formationIndex = Math.round(formationIndex(p.domainScores));

  // A few focus-check micro-tests trending faster/sharper over time.
  const fc = SPEC.focusCheck;
  for (let i = 0; i < fc.count; i++) {
    const t = fc.count > 1 ? i / (fc.count - 1) : 1;
    const daysAgo = Math.round(84 - t * 80); // spread across the full 90-day window (~84d ago -> ~4d ago)
    p.focusChecks.push({
      date: dayStr(today, daysAgo),
      ts: isoAt(today, daysAgo, 10),
      medianMs: Math.round(fc.medianMsHigh - (fc.medianMsHigh - fc.medianMsLow) * t),
      score: Math.round(fc.scoreLow + (fc.scoreHigh - fc.scoreLow) * t),
      trials: 12,
    });
  }

  return p;
}
