// demo.js — a deterministic SAMPLE profile for previewing the populated app.
//
// WHY: an investor or prospective user should see the whole of Forma — radar,
// trends, coach, Progress — without first doing the baseline and weeks of
// practice. Demo Mode (app.js) swaps this sample into memory.
//
// NON-DESTRUCTIVE: Demo Mode never writes to disk. app.js's save() is a no-op
// while demo is on, so the real profile in localStorage is never touched; the
// sample lives only in memory and vanishes on reload or exit.
//
// HONEST: every number here is ILLUSTRATIVE — generated to show the interface,
// not a measurement of any real person. The app shows a persistent "sample data"
// banner the whole time, so it can't be mistaken for a real profile.
//
// GUARDRAIL: the optional Spiritual Life / interior track is OFF here, and no
// interior/faith content appears anywhere — the same wall the real app enforces.
//
// Deterministic: no RNG (seeded by index, like team.js's sampleCohort), so the
// sample is identical every time and stable to test.

import { DOMAINS } from './domains.js';
import { formationIndex } from './scoring.js';
import { todayStr } from './progress.js';
import { bandIndex } from './milestones.js';

const DAY_MS = 86400000;

// ---- THE SAMPLE SPEC ---------------------------------------------------------
// One auditable object holds all of the sample's numbers and copy, so the whole
// fiction is easy to read, tune, and verify against the brand. Generated by the
// validity / coach-voice / design review (workflow forma-demo-spec).
export const SPEC = {
  persona: {
    name: 'Daniel R.',
    role: 'Senior product manager',
    oneLine: 'A mid-career PM who came to Forma after noticing his focus had gone shallow and his patience short, wanting to track whether deliberate practice actually moves the needle.',
  },
  // Current 0-100 per capacity — a lumpy, believable radar. Strengths: Values 74,
  // Reading 71, Judgment 66, Presence 63. Genuine growth areas (the lows that
  // brought him in): Emotional Regulation 41, Frustration Tolerance 44, Attention 48.
  current: {
    attention: 48, memory: 57, reading: 71, persistence: 44, judgment: 66,
    ai_autonomy: 52, presence: 63, communication: 58, emotion_regulation: 41, values: 74,
  },
  // ~90 days ago. Mostly lower (real, modest growth), but HONEST and non-monotonic:
  // Presence is essentially flat (62->63), Emotional Regulation is actually DOWN
  // (45->41) — a hard season the instrument surfaces rather than smooths over.
  baseline: {
    attention: 41, memory: 49, reading: 65, persistence: 38, judgment: 61,
    ai_autonomy: 47, presence: 62, communication: 51, emotion_regulation: 45, values: 68,
  },
  // Formation Index per week, oldest first, ~90 days. Rises 51->57 but bumpy: an
  // early dip (wk3), a mid-run plateau (wks7-9), a small pullback (wk10). Not a line.
  weeklyIndex: [51, 52, 50, 53, 54, 53, 54, 55, 55, 54, 56, 57, 57],
  streak: { current: 6, longest: 17 },
  focusCheck: { count: 7, medianMsLow: 372, medianMsHigh: 521, scoreLow: 49, scoreHigh: 72 },
  // The general "Today" coach thread — solution-focused, warm, specific. Anchors on
  // his STEADIEST capacity (Relational Presence), without overclaiming it as #1. No interior.
  coachGeneral: [
    { role: 'coach', content: 'You stayed with people better than almost anything you did this stretch — Relational Presence is your steadiest capacity, and it held even on your busiest weeks. That kind of staying-power with someone is rare. When did being with a person, without trying to fix it, go best for you lately?' },
    { role: 'user', content: 'Probably my one-on-one with Priya on Tuesday. I just listened instead of jumping to solutions for once.' },
    { role: 'coach', content: 'That’s worth noticing — you didn’t reach for the fix, and the conversation was better for it. What was different about Tuesday that let you do that? If you can name the one thing, you can set it up again on purpose.' },
    { role: 'user', content: 'Honestly I think I just hadn’t checked my phone right before. I went in with a clear head.' },
    { role: 'coach', content: 'Then you already found the lever — a clear head going in, not a longer to-do list. What would it cost you to leave the phone at your desk before your next one-on-one and see if it holds?' },
  ],
  // Reading is a STRENGTH (71). The coaching is about an eroded reading HABIT
  // (skimming, AI summaries), NOT a weak score — consistent with the number.
  coachDomainId: 'reading',
  coachDomain: [
    { role: 'coach', content: 'You just finished the deep-reading passage, and your comprehension is genuinely strong — Deep Reading is one of your higher capacities. But the same pattern showed up that’s been there for weeks: you read the opening closely, then your speed climbs toward the end and the detail questions slip. The skill is there. What I’m curious about is the habit — when in your real week do you actually read something slowly, all the way through?' },
    { role: 'user', content: 'Almost never anymore. I skim everything. I’ll read the summary an AI gives me and tell myself I’ll read the real thing later. I never do.' },
    { role: 'coach', content: 'That’s honest, and it’s most of the work — you can see the trade you’re making. Skimming isn’t the enemy; living only in summaries is, because the thinking happens inside the long argument, not the recap. Here’s one small thing: pick one article this week that actually matters to you, and read just the first three pages on paper or full-screen, phone in another room. Not the whole thing — just far enough to feel what reading at depth is like again. Would you try that with something you’d genuinely want to have read?' },
  ],
  goals: [
    { domain: 'reading', text: 'Read one real article a week to the end on full screen, phone in another room — no summary first.' },
    { domain: 'emotion_regulation', text: 'When a deadline spikes my stress, take three slow breaths and name the feeling before I reply to the thread.' },
    { domain: 'ai_autonomy', text: 'On one task a day, draft my own first version before I open an AI tool, so the thinking starts as mine.' },
  ],
  noticing: 'Your Relational Presence and Judgment have held steady through the run — both still Strong — while the most room to grow right now is in Emotional Regulation and Frustration Tolerance. Your reading comprehension is strong; the practice of reading deeply is the habit worth rebuilding.',
  // Design / chrome copy. The word "Sample" and the fictional name are literally present — honesty over subtlety.
  bannerText: 'Sample profile — “Daniel R.” is fictional. These numbers are illustrative, not a real measurement.',
  exitCta: 'Exit sample',
  exitToast: 'Back to your own Forma.',
  welcomeButton: 'See a sample profile',
  welcomeButtonSub: 'Explore the whole app, already populated — a fictional example, no baseline required.',
  settingsLabel: 'Open sample profile',
  settingsHelp: 'Loads a fictional example so you can show Forma fully populated. Your own data is untouched — exit anytime to return to it.',
  honestyNote: 'Every score, trend, and coach line here is generated to demonstrate the interface — it isn’t a measurement of anyone, and “Daniel R.” is not a real person.',
};

function dayStr(today, daysAgo) {
  return todayStr(new Date(today.getTime() - daysAgo * DAY_MS));
}
function isoAt(today, daysAgo, hour) {
  const d = new Date(today.getTime() - daysAgo * DAY_MS);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

// A representative exercise type per capacity (all real types), so Recent
// sessions and per-capacity threads read naturally.
const TYPE_FOR = {
  attention: 'attend', memory: 'span', reading: 'reading', persistence: 'series',
  judgment: 'crt', ai_autonomy: 'reliance', presence: 'contemplation',
  communication: 'comm', emotion_regulation: 'steu', values: 'reflection',
};

// Build the per-capacity longitudinal log that drives the sparklines + deltas:
// a few points per domain marching from baseline toward current over 90 days.
function buildHistory(today) {
  const ids = DOMAINS.map((d) => d.id).filter((id) => SPEC.current[id] != null);
  const history = [];
  const STEPS = 5; // points per capacity across the window
  ids.forEach((id) => {
    const from = SPEC.baseline[id] != null ? SPEC.baseline[id] : SPEC.current[id];
    const to = SPEC.current[id];
    for (let k = 0; k < STEPS; k++) {
      const t = k / (STEPS - 1);
      // Ease the climb and add a tiny seeded wobble so the line isn't a ruler.
      const wob = ((id.length * 7 + k * 13) % 5) - 2; // -2..2, deterministic
      const val = Math.round(from + (to - from) * t + (k === 0 || k === STEPS - 1 ? 0 : wob));
      const daysAgo = Math.round(84 - t * 78); // ~84d ago -> ~6d ago
      history.push({
        date: dayStr(today, daysAgo),
        domain: id,
        exerciseType: TYPE_FOR[id] || 'reflection',
        rawScore: val,
        newDomainScore: k === STEPS - 1 ? to : val, // last point lands on current
        formationIndex: SPEC.weeklyIndex[Math.min(SPEC.weeklyIndex.length - 1, Math.round(t * (SPEC.weeklyIndex.length - 1)))],
      });
    }
  });
  return history;
}

// A believable run of recent, scored sessions (one a day for the last stretch),
// rotating through capacities — what Recent sessions lists.
function buildSessions(today) {
  const ids = DOMAINS.map((d) => d.id).filter((id) => SPEC.current[id] != null);
  const sessions = [];
  const N = 9;
  for (let i = 0; i < N; i++) {
    const daysAgo = N - 1 - i; // oldest first ... today
    const id = ids[(i * 3 + 2) % ids.length]; // deterministic rotation
    const cur = SPEC.current[id];
    const raw = Math.max(0, Math.min(100, cur + (((i * 11 + id.length * 5) % 11) - 5))); // cur ±5
    sessions.push({
      date: dayStr(today, daysAgo),
      hour: 8 + (i % 6),
      ts: isoAt(today, daysAgo, 8 + (i % 6)),
      exerciseId: 'demo-' + id + '-' + i,
      type: TYPE_FOR[id] || 'reflection',
      domain: id,
      rawScore: raw,
      prevDomainScore: cur - 1,
      newDomainScore: cur,
      priorBandPeak: bandIndex(cur),
      unscored: false,
      response: {},
    });
  }
  return sessions;
}

// Construct the full sample profile. `today` is injectable for stable tests.
export function buildDemoProfile(today = new Date()) {
  const p = {
    version: 1,
    createdAt: isoAt(today, 92, 9),
    demo: true, // an in-memory marker; the real profile never carries this
    settings: { provider: 'anthropic', apiKey: '', model: 'claude-opus-4-8', name: SPEC.persona.name, faithTrack: false, researchEndpoint: '' },
    baseline: { date: dayStr(today, 90), domainScores: { ...SPEC.baseline }, responses: {}, method: 'quick' },
    domainScores: { ...SPEC.current },
    sessions: buildSessions(today),
    history: buildHistory(today),
    indexHistory: [],
    focusChecks: [],
    plan: null,
    goals: SPEC.goals.map((g, i) => ({ id: 'demo-goal-' + i, domain: g.domain, text: g.text, createdAt: isoAt(today, 30 - i * 6, 9), done: false })),
    streak: { current: SPEC.streak.current, longest: SPEC.streak.longest, lastDate: dayStr(today, 0) },
    coachLog: SPEC.coachGeneral.map((m, i) => ({ role: m.role, content: m.content, ts: isoAt(today, 0, 8 + i) })),
    coachThreads: { [SPEC.coachDomainId]: SPEC.coachDomain.map((m, i) => ({ role: m.role, content: m.content, ts: isoAt(today, 1, 17 + i) })) },
    coachHistory: {},
    coachDay: dayStr(today, 0),
    research: { consent: false, consentedAt: null, demographics: {}, queue: [], installId: '', nextSeq: 0 },
    contact: { consent: false, email: '', consentedAt: null },
    release: { consent: false, recipient: '', scope: 'snapshot', snapshot: null, consentedAt: null },
    bandPeak: {},
  };

  // High-water band latch per capacity, so milestone checks don't misfire.
  DOMAINS.forEach((d) => { if (p.domainScores[d.id] != null) p.bandPeak[d.id] = bandIndex(p.domainScores[d.id]); });

  // Index trend across ~90 days, oldest first. The final point is reconciled to
  // the true mean of the current scores, so the headline number is honest.
  const W = SPEC.weeklyIndex;
  W.forEach((fi, i) => {
    const daysAgo = Math.round(90 - (i * 90) / (W.length - 1));
    p.indexHistory.push({ date: dayStr(today, daysAgo), formationIndex: fi });
  });
  p.indexHistory[p.indexHistory.length - 1].formationIndex = Math.round(formationIndex(p.domainScores));

  // A few focus-check micro-tests trending faster/sharper over time.
  const fc = SPEC.focusCheck;
  for (let i = 0; i < fc.count; i++) {
    const t = fc.count > 1 ? i / (fc.count - 1) : 1;
    const daysAgo = Math.round(40 - t * 38);
    p.focusChecks.push({
      date: dayStr(today, daysAgo),
      ts: isoAt(today, daysAgo, 10),
      medianMs: Math.round(fc.medianMsHigh - (fc.medianMsHigh - fc.medianMsLow) * t),
      score: Math.round(fc.scoreLow + (fc.scoreHigh - fc.scoreLow) * t),
      trials: 12,
    });
  }

  return p;
}
